MB_SOURCES = $(wildcard research/*.md)
IPY_SOURCES = $(wildcard research/*.ipynb)
HTML_TEMPLATE_SOUCES = $(wildcard src/*_template.html)
TARGETS =	$(patsubst research/%.md,static/research/%.html,${MB_SOURCES}) \
			$(patsubst research/%.ipynb,static/research/%.html,${IPY_SOURCES}) \
			$(patsubst src/%_template.html,static/%.html,${HTML_TEMPLATE_SOUCES})

DOTA_TIMES_OUT = tmp/dota-times-out
DOTA_TIMES_SRC = ./scripts/dota-times.hs
PLACEHOLDER_REPLACE_SH = ./scripts/replace-placeholders.sh
TMP_FILES = ${DOTA_TIMES_OUT}
TMP_DIR = tmp/
RESEARCH_OUT_DIR = static/research
BUILD_DIRS = ${RESEARCH_OUT_DIR} ${TMP_DIR}

all: ${BUILD_DIRS} ${TARGETS}

depcheck:
	pandoc -v
	runhaskell --version
	sed --version

${BUILD_DIRS}:
	mkdir -p $@

# previously
# find . -iname '*.md' -exec bash -c 'mdtohtml "$1" "${1/%.md/.html}"' _ {} '.html' ';'
static/research/%.html: research/%.md ${RESEARCH_OUT_DIR}
	pandoc --standalone --css=/style.css $< --metadata pagetitle=$(notdir $(basename $<)) -o $@
	sed -i '1i<!-- generated by $< -->' $@

static/research/%.html: research/%.ipynb ${RESEARCH_OUT_DIR}
	jupyter nbconvert $< --stdout --to html --embed-images --theme dark > $@
	sed -i '1i<!-- generated by $< -->' $@

${DOTA_TIMES_OUT}: ${DOTA_TIMES_SRC} ${TMP_DIR}
	runhaskell $< html 35 > ${DOTA_TIMES_OUT}
	sed -i '1i<!-- generated by $< -->' $@

static/rosh.html: src/rosh_template.html ${DOTA_TIMES_OUT} ${PLACEHOLDER_REPLACE_SH}
	bash ${PLACEHOLDER_REPLACE_SH} $< DOTA_TIMES_HS ${DOTA_TIMES_OUT} > $@
	sed -i '1i<!-- generated by $< -->' $@

clean:
	${RM} ${TARGETS} ${TMP_FILES}
	rmdir ${BUILD_DIRS} > /dev/null 2>&1 || true

re: clean all
