MB_SOURCES = $(wildcard research/*.md)
IPY_SOURCES = $(wildcard research/*.ipynb)
HTML_TEMPLATE_SOUCES = $(wildcard src/*_template.html)
TARGETS =	$(patsubst research/%.md,static/research/%.html,${MB_SOURCES}) \
			$(patsubst research/%.ipynb,static/research/%.html,${IPY_SOURCES}) \
			$(patsubst src/%_template.html,static/%.html,${HTML_TEMPLATE_SOUCES})

DOTA_TIMES_OUT = tmp/dota-times-out
DOTA_TIMES_SRC = ./scripts/dota-times.hs
PLACEHOLDER_REPLACE_SH = ./scripts/replace-placeholders.sh
TMP_FILES = ${DOTA_TIMES_OUT}
DIRS = static/research tmp/

all: ${DIRS} ${TARGETS}

depcheck:
	pandoc -v

${DIRS}:
	mkdir -p $@

# previously
# find . -iname '*.md' -exec bash -c 'mdtohtml "$1" "${1/%.md/.html}"' _ {} '.html' ';'
static/research/%.html: research/%.md
	pandoc --standalone --css=/style.css $< --metadata pagetitle=$(notdir $(basename $<)) -o $@
	sed -i '1i<!-- generated by $< -->' $@

static/research/%.html: research/%.ipynb
	jupyter nbconvert $< --stdout --to html --embed-images --theme dark > $@
	sed -i '1i<!-- generated by $< -->' $@

${DOTA_TIMES_OUT}: tmp/ ${DOTA_TIMES_SRC}
	runhaskell ${DOTA_TIMES_SRC} html 35 > ${DOTA_TIMES_OUT}
	sed -i '1i<!-- generated by ${DOTA_TIMES_SRC} -->' $@

static/%.html: src/%_template.html ${DOTA_TIMES_OUT} ${PLACEHOLDER_REPLACE_SH}
	bash ${PLACEHOLDER_REPLACE_SH} $< DOTA_TIMES_HS ${DOTA_TIMES_OUT} > $@
	sed -i '1i<!-- generated by $< -->' $@

clean:
	${RM} ${TARGETS} ${TMP_FILES}
	rmdir ${DIRS} > /dev/null || true

re: clean all
