MB_SOURCES = $(wildcard research/*.md)
IPY_SOURCES = $(wildcard research/*.ipynb)
TARGETS = $(patsubst research/%.md,static/research/%.html,${MB_SOURCES}) $(patsubst research/%.ipynb,static/research/%.html,${IPY_SOURCES})

DIRS = static/research

all: ${DIRS} ${TARGETS}

depcheck:
	pandoc -v

${DIRS}:
	mkdir -p $@

# previously
# find . -iname '*.md' -exec bash -c 'mdtohtml "$1" "${1/%.md/.html}"' _ {} '.html' ';'
static/research/%.html: research/%.md
	pandoc --standalone --css=/style.css $< --metadata pagetitle=$(notdir $(basename $<)) -o $@
	sed -i '1i<!-- generated by $< -->' $@

static/research/%.html: research/%.ipynb
	jupyter nbconvert $< --stdout --to html --embed-images --theme dark > $@
	sed -i '1i<!-- generated by $< -->' $@

clean:
	${RM} ${TARGETS}
	rmdir ${DIRS} > /dev/null || true

re: clean all
